<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>CrawfisSoftware.Tiling</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>

    <!-- Fix NuGet package id -->
    <PackageId>CrawfisSoftware.MazeTilings</PackageId>

    <!-- Optional: prevent doubled assembly name -->
    <AssemblyName>$(MSBuildProjectName)</AssemblyName>

    <!-- Show README on NuGet -->
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DocumentationFile>$(SolutionDir)bin\Documentation\CrawfisSoftware.MazeTilings.xml</DocumentationFile>
    <OutputPath>$(SolutionDir)bin\Debug\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <OutputPath>$(SolutionDir)bin\Release\</OutputPath>
    <DocumentationFile>$(SolutionDir)bin\Documentation\CrawfisSoftware.MazeTilings.xml</DocumentationFile>
  </PropertyGroup>

  <PropertyGroup>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CrawfisSoftware.Maze" Version="0.1.2" />
    <PackageReference Include="CrawfisSoftware.Tiling" Version="0.2.0" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>